### ISSUE TITLE
求解惑 wosttrace和besttrace和nexttrace这3个有什么区别不

### ISSUE THREAD

**Issue by CodeGoMe** [Joseph-ink/Useful-tools#1]
求教大佬 我用下来感觉除了显示的不一样 其他好像没什么区别啊 但是别人说区别很大 感激不尽

**Comment by Joseph-ink** [comment]
非大佬
besttrace前期有传闻要收费......并且它的gui客户端在mac上很难用，所以就弃用了
worsttrace应该还是能用，但是它缺arm的支持
新的nexttrace没啥毛病，简单好用
